const UserModel = require('../models/UserModel');
const otp_generator = require('otp-generator');
const bcrypt = require('bcrypt');
const jwt = require('jsonwebtoken');

const sendEmail = require('../email_service/Email');

const register = async (req, res) => {
  try {
    // console.log(req.body);

    const isUserExisting = await UserModel.findOne({ email: req.body.email });

    if (isUserExisting) {
      console.log('User already exists.');
      return res
        .status(400)
        .json({ msg: `User with ${req.body.email} already exists` });
    }

    const verificationToken = otp_generator.generate(6, {
      upperCaseAlphabets: false,
      specialChars: false,
    });

    const expires = new Date();

    expires.setMinutes(expires.getMinutes() + 5);

    const hashedPassword = await bcrypt.hash(req.body.password, 10);

    const newUser = await UserModel({
      email: req.body.email,
      username: req.body.username,
      password: hashedPassword,
      verificationToken: {
        token: verificationToken,
        expires: expires,
      },
    });

    console.log(newUser);

    await newUser.save();

    const emailBody = `<p>Please click on the link to verify your account. <b>http://localhost:4000/user/verify/${verificationToken}</b></p>`;

    const subject = 'Please Verify Your Account';

    await sendEmail(req.body.email, subject, emailBody);

    res.json({ msg: 'Verification link sent to your email.' });
  } catch (error) {
    res.json({ msg: 'Something went wrong.' });
  }
};

const login = async (req, res) => {
  try {
    const isUserExisting = await UserModel.findOne({ email: req.body.email });

    // console.log(isUserExisting);

    const password = otp_generator.generate(12, {
      upperCaseAlphabets: true,
      lowerCaseAlphabets: true,
      digits: true,
      specialChars: true,
    });

    const hashedPassword = await bcrypt.hash(password, 10);

    if (!isUserExisting) {
      if (req.body.autoGenerated) {
        const newUser = await UserModel({
          email: req.body.email,
          username: req.body.username,
          password: hashedPassword,
          isVerified: true,
        });

        await newUser.save();

        const jwtPayload = {
          id: newUser._id,
        };

        const token = jwt.sign(jwtPayload, process.env.SECRET, {
          expiresIn: '1h',
        });

        const emailBody = `<p>Account created successfully! Your password is <b>${password}</b>.Please change it.</p>`;

        const subject = 'Account created VIA Social.';

        await sendEmail(req.body.email, subject, emailBody);

        return res.status(200).json({ msg: 'Logged in via social.', token });
      }

      return res
        .status(400)
        .json({ msg: `User with ${req.body.email} does not exist` });
    }

    if (!isUserExisting.isVerified) {
      return res.status(400).json({
        msg: `User is not verified. Please click the link in your email to verify.`,
      });
    }

    const isPasswordCorrect = await bcrypt.compare(
      req.body.password,
      isUserExisting.password
    );

    if (!isPasswordCorrect) {
      return res.status(400).json({ msg: 'Invalid credentials' });
    }

    // Create a JWT

    const jwtPayload = {
      id: isUserExisting._id,
    };

    const token = jwt.sign(jwtPayload, process.env.SECRET, {
      expiresIn: '1h',
    });

    res.json({ msg: 'Welcome.', token });
  } catch (error) {
    res
      .status(500)
      .json({ msg: 'Something went wrong when trying to log in.' });
  }
};

const verifyUser = async (req, res) => {
  try {
    const { token } = req.params;

    const isTokenValid = await UserModel.findOne({
      'verificationToken.token': token,
      'verificationToken.expires': { $gt: new Date() },
    });

    if (!isTokenValid) {
      return res.send(
        `<p>Token invalid or expired.</p><a href="http://localhost:4000/user/resendVerification/${token}">Resend Verification Email</a>`
      );
    }

    if (isTokenValid.isVerified) {
      res.send('<p>Account is already verified. Please log in.</p>');
    }

    isTokenValid.isVerified = true;

    await isTokenValid.save();

    res.send('Your account is verified!');
  } catch (error) {
    console.log(error);
  }
};

const resendVerification = async (req, res) => {
  try {
    const { token } = req.params;

    const user = await UserModel.findOne({
      'verificationToken.token': token,
      isVerified: false,
    });

    if (!user) {
      return res.send('User not found or already verified.');
    }

    const verificationToken = otp_generator.generate(6, {
      upperCaseAlphabets: false,
      specialChars: false,
    });

    const expires = new Date();

    expires.setMinutes(expires.getMinutes() + 3);

    user.verificationToken = {
      expires: expires,
      token: verificationToken,
    };

    await user.save();

    // Send email

    const emailBody = `<p>Please click on the link to verify your account. <b>http://localhost:4000/user/verify/${verificationToken}</b></p>`;

    const subject = 'Verificaiton Email';

    await sendEmail(user.email, subject, emailBody);

    res.send('Please check your email for a new verification link.');
  } catch (error) {
    console.error(error);

    res.send('Something went wrong.');
  }
};

const updateUser = async (req, res) => {
  try {
    const { id } = req.decodedData;
    const { type } = req.body;

    const user = await UserModel.findById(id);

    switch (type) {
      case 'username': {
        user.username = req.body.newUserDetails.username;
        await user.save();

        // send email?
        
        // const emailBody = `<p>Username updated.</p>`;

        // const subject = 'User Updated Successfully';

        // await sendEmail(user.email, subject, emailBody);
        break
      }
      case 'email': {
        user.email = req.body.newUserDetails.email;
        await user.save();

        const emailBody = `<p>Email updated.</p>`;

        const subject = 'Email Updated Successfully';

        await sendEmail(user.email, subject, emailBody);
        break
      }
      case 'password': {
        const hashedPassword = await bcrypt.hash(
          req.body.newUserDetails.password,
          10
        );

        user.password = hashedPassword;

        await user.save();

        const emailBody = `<p>You updated your password.</p>`;

        const subject = 'Password updated successfully.';

        await sendEmail(user.email, subject, emailBody);
        break
      }
    }

    res.json({ msg: 'User updated successfully.' });
  } catch (error) {
    console.log(error);
    console.error();
    res.json({ msg: 'Something went wrong.' });
  }
};

const forgotPassword = async (req, res) => {
  try {
    console.log(req.body);

    const isUserExisting = await UserModel.findOne({ email: req.body.email });

    if (!isUserExisting) {
      return res
        .status(400)
        .json({ msg: `User with ${req.body.email} doesn't exists.` });
    }

    if (req.body.isOTPVerified) {
      const hashedPassword = await bcrypt.hash(req.body.password, 10);

      isUserExisting.password = hashedPassword;

      await isUserExisting.save();

      const emailBody = `<p>Your password was reset was successful.`;

      const subject = 'Password Reset Successfully';

      await sendEmail(isUserExisting.email, subject, emailBody);

      return res.status(200).json({ msg: 'Password Reset Successfully.' });
    }

    const OTP = otp_generator.generate(6, {
      upperCaseAlphabets: false,
      specialChars: false,
    });

    const expires = new Date();

    expires.setMinutes(expires.getMinutes() + 5);

    isUserExisting.OTP_VerificationToken = {
      OTP,
      expires,
    };

    await isUserExisting.save();

    const emailBody = `<p>Your OTP for passoword reset request is <b>${OTP}</b> <br> OTP expires in 5 mins</p>`;

    const subject = 'Reset Your Password';

    await sendEmail(isUserExisting.email, subject, emailBody);

    res.status(200).json({ msg: 'OTP Sent Successfully.' });
  } catch (error) {
    console.log(error);

    res.status(500).json({ msg: `Something went wrong.` });
  }
};

const verifyPasswordOTP = async (req, res) => {
  try {
    console.log(req.body);

    const { OTP } = req.body;

    const isOtpValid = await UserModel.findOne({
      'OTP_VerificationToken.OTP': OTP,
      'OTP_VerificationToken.expires': { $gt: new Date() },
    });

    console.log(isOtpValid);

    if (!isOtpValid) {
      return res.status(400).json({ msg: 'OTP Expired' });
    }

    res.status(200).json({ msg: 'OTP Verified Successfully' });
  } catch (error) {
    res.status(500).json({ msg: 'Something went wrong.' });
  }
};

const getUserDetails = async (req, res) => {
  try {
    // console.log(req.decodedData);

    const { id } = req.decodedData;

    const userData = await UserModel.findById(id);

    const user = {
      email: userData.email,
      username: userData.username,
    };

    console.log(user);

    res.json({ user: user });
  } catch (error) {
    res.status(500).json({ msg: 'Something went wrong.' });
  }
};

module.exports = {
  register,
  login,
  verifyUser,
  resendVerification,
  updateUser,
  forgotPassword,
  verifyPasswordOTP,
  getUserDetails,
};
