import React, { useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import toast from 'react-hot-toast';
import axios from 'axios';
import {
  GoogleLoginButton,
  FacebookLoginButton,
} from 'react-social-login-buttons';
import { useGoogleLogin } from '@react-oauth/google';
import { motion } from 'framer-motion';

import styles from './login.module.css';
import { emailRegex, passwordRegex } from '../../utils/RegEx';
import FacebookLogin from '../FacebookLogin';
import Loader from '../loader/Loader';

function Login() {
  const [userDetails, setUserDetails] = useState({
    password: '',
    email: '',
  });
  const [show, setShow] = useState(false);
  const [isLoading, setIsLoading] = useState(false);

  const navigate = useNavigate();

  function handleInputChange(e) {
    const { name, value } = e.target;

    setUserDetails((prev) => ({
      ...prev,
      [name]: value,
    }));
  }

  const handleLogin = async () => {
    // if (!passwordRegex.test(userDetails.password)) {
    //   toast.error(
    //     'Password must be at least 8 characters and must include at least one special character and one number'
    //   );
    //   return;
    // }
    try {
      setIsLoading(true);
      const response = await axios.post(
        `${import.meta.env.VITE_BASE_SERVER_URL}/user/login`,
        userDetails
      );
      // console.log(response);
      toast.success(response.data.msg);

      localStorage.setItem('token', response.data.token);

      navigate('/home');
      setIsLoading(false);
    } catch (error) {
      // console.error(error);
      toast.error(error.response.data.msg);
      setIsLoading(false);
    }
  };

  const handleContinueWithGoogle = useGoogleLogin({
    onSuccess: async (response) => {
      // console.log(response);

      const res = await axios.get(
        'https://www.googleapis.com/oauth2/v3/userinfo',
        {
          headers: { Authorization: `Bearer ${response.access_token}` },
        }
      );
      console.log(res.data);

      const newUser = {
        username: res.data.name,
        email: res.data.email,
        autoGenerated: true,
      };

      console.log(newUser);

      try {
        const response = await axios.post(
          `${import.meta.env.VITE_BASE_SERVER_URL}/user/login`,
          newUser
        );
        // console.log(response);
        toast.success(response.data.msg);

        localStorage.setItem('token', response.data.token);

        navigate('/home');
      } catch (error) {
        // console.error(error);
        toast.error(error.response.data.msg);
      }
    },
    onError: (error) => {
      console.log(error);
    },
  });

  return (
    <motion.div
     initial={{ opacity: 0, y: 100 }}
      animate={{ opacity: 1, y: 0 }}
      exit={{ opacity: 0, y: -50 }}
      transition={{
        type: "spring",
        stiffness: 200,
        damping: 20,
        duration: 0.5,
      }}
      className={styles.container}
    >
      <div className={styles.formContainer}>
        <h2>Login...</h2>

        <div className={styles.socials}>
          <div>
            <FacebookLogin />
          </div>
          <div onClick={handleContinueWithGoogle}>
            <GoogleLoginButton></GoogleLoginButton>
          </div>
        </div>
        <div className={styles.inputContainer}>
          <input
            value={userDetails.email}
            placeholder='Enter your email'
            type='email'
            name='email'
            onChange={handleInputChange}
          />
          <div className={styles.passwordContainer}>
            <input
              value={userDetails.password}
              placeholder='Enter your password'
              type={show ? 'text' : 'password'}
              name='password'
              onChange={handleInputChange}
            />
            <button
              onClick={() => {
                setShow(!show);
              }}
            >
              {show ? 'HIDE' : 'SHOW'}
            </button>
          </div>

          <button disabled={isLoading} onClick={handleLogin}>
            {isLoading ? <Loader /> : 'Login'}
          </button>
        </div>

        <div className={styles.footer}>
          <Link to={'/signup'}>Don't have an account? Signup</Link>
          <Link to={'/forgot-password'}>Forgot Password?</Link>
        </div>
      </div>
    </motion.div>
  );
}

export default Login;
